# postgres-ha-values.yaml

postgresql:
  replicaCount: 2
  username: "admin"
  database: "hdp"

pgpool:
  enabled: true
  extendedConfig: |
    read_write_splitting_method = 'sql_parser'
    load_balance_mode = on

  # =========================================================
  # CẤU HÌNH BIẾN PGPOOL THÀNH SERVICE LOADBALANCER
  # =========================================================
  service:
    type: LoadBalancer
    port: 5432
    
    # Mẹo chuyên nghiệp cho MetalLB: Gán IP tĩnh
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.1.202"