apiVersion: v1
kind: Service
metadata:
  name: redis-cache-external
  namespace: hdp
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.206"
spec:
  type: LoadBalancer
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    role: replication
    redis-role: master